### ISSUE TITLE
Issue running on M1 mac using conda

### ISSUE THREAD

**Issue by axeljeremy7** [simonw/shot-scraper#115]
Traceback (most recent call last):
  File "/Users/axeljeremy/opt/miniconda3/bin/shot-scraper", line 5, in <module>
    from shot_scraper.cli import cli
  File "/Users/axeljeremy/opt/miniconda3/lib/python3.9/site-packages/shot_scraper/cli.py", line 6, in <module>
    from playwright.sync_api import sync_playwright, Error, TimeoutError
  File "/Users/axeljeremy/opt/miniconda3/lib/python3.9/site-packages/playwright/sync_api/__init__.py", line 25, in <module>
    import playwright.sync_api._generated
  File "/Users/axeljeremy/opt/miniconda3/lib/python3.9/site-packages/playwright/sync_api/_generated.py", line 25, in <module>
    from playwright._impl._accessibility import Accessibility as AccessibilityImpl
  File "/Users/axeljeremy/opt/miniconda3/lib/python3.9/site-packages/playwright/_impl/_accessibility.py", line 17, in <module>
    from playwright._impl._connection import Channel
  File "/Users/axeljeremy/opt/miniconda3/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 34, in <module>
    from greenlet import greenlet
  File "/Users/axeljeremy/opt/miniconda3/lib/python3.9/site-packages/greenlet/__init__.py", line 29, in <module>
    from ._greenlet import _C_API # pylint:disable=no-name-in-module
ImportError: dlopen(/Users/axeljeremy/opt/miniconda3/lib/python3.9/site-packages/greenlet/_greenlet.cpython-39-darwin.so, 0x0002): tried: '/Users/axeljeremy/opt/miniconda3/lib/python3.9/site-packages/greenlet/_greenlet.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/axeljeremy/opt/miniconda3/lib/python3.9/site-packages/greenlet/_greenlet.cpython-39-darwin.so' (no such file), '/Users/axeljeremy/opt/miniconda3/lib/python3.9/site-packages/greenlet/_greenlet.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

**Comment by timc3** [comment]
I am running on Apple Silicon (M2) and using Conda, and I haven't come across this error. Are you sure you installed Conda from scratch on your M1 with Python to get the correct architecture?
