### ISSUE TITLE
`shot-scraper multi` should be able to ignore errors and keep on running

### ISSUE THREAD

**Issue by ryancheley** [simonw/shot-scraper#50]
**Describe the bug**
When running `shot-scraper multi shots.yml` if one of the sites times out, the cli stops at that site instead of continuing on

shots.yml

```
- output: w3c.org.png
  url: https://www.w3.org/
- output: cnn.com.png
  url: http://www.cnn.com/
- output: example.com.png
  url: http://www.example.com/
```

```
❯ shot-scraper multi shots.yml
Screenshot of 'https://www.w3.org/' written to 'w3c.org.png'
Traceback (most recent call last):
  File "/Users/ryan/.local/bin/shot-scraper", line 8, in <module>
    sys.exit(cli())
  File "/Users/ryan/.local/pipx/venvs/shot-scraper/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ryan/.local/pipx/venvs/shot-scraper/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/ryan/.local/pipx/venvs/shot-scraper/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ryan/.local/pipx/venvs/shot-scraper/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ryan/.local/pipx/venvs/shot-scraper/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/ryan/.local/pipx/venvs/shot-scraper/lib/python3.10/site-packages/shot_scraper/cli.py", line 208, in multi
    take_shot(context, shot)
  File "/Users/ryan/.local/pipx/venvs/shot-scraper/lib/python3.10/site-packages/shot_scraper/cli.py", line 469, in take_shot
    page.goto(url)
  File "/Users/ryan/.local/pipx/venvs/shot-scraper/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 7345, in goto
    self._sync(
  File "/Users/ryan/.local/pipx/venvs/shot-scraper/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 88, in _sync
    return task.result()
  File "/Users/ryan/.local/pipx/venvs/shot-scraper/lib/python3.10/site-packages/playwright/_impl/_page.py", line 487, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/Users/ryan/.local/pipx/venvs/shot-scraper/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 122, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/Users/ryan/.local/pipx/venvs/shot-scraper/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/Users/ryan/.local/pipx/venvs/shot-scraper/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "http://www.cnn.com/", waiting until "load"
============================================================
```

**To Reproduce**
1. Create a file `shots.yml` 
```
- output: w3c.org.png
  url: https://www.w3.org/
- output: cnn.com.png
  url: http://www.cnn.com/
- output: example.com.png
  url: http://www.example.com/
```
2. run `shot-scraper multi shots.yml`
3. See that the second site causes an error and does not move onto the third site

**Expected behavior**
If a timeout occurs, the tool should output an error has occurred and move onto the next site to process, something like this:

```
Screenshot of 'https://www.w3.org/' written to 'w3c.org.png'
Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "http://www.cnn.com/", waiting until "load"
============================================================
Screenshot of 'http://www.cnn.com/' written to 'cnn.com.png'
Screenshot of 'http://www.example.com/' written to 'example.com.png'
```

**Additional context**
This may be a duplicate of #48, or perhaps just related

**Comment by simonw** [comment]
Yeah, I agree: the tool should log an error but keep on working through the rest of the file.

Although maybe there should be a flag for something like `--fail-on-error` so that if you are running in CI you can have the task fail noisily on any errors?

**Comment by ryancheley** [comment]
@simonw added a new flag `--fail-on-error` based on your suggestion above. 

I also update the README.md to include the new flag (using `cog -r README.md` to regenerate the file ... I ❤️  `cog` 😄 )

**Comment by simonw** [comment]
I'm going to add the `--timeout` option to `multi` which @palewire added to `shot` in:
#47

**Comment by simonw** [comment]
Adding the timeout option revealed a bug in this implementation:
```
shot-scraper multi ../lots.yml --timeout 5
Traceback (most recent call last):
  File "/Users/simon/.local/share/virtualenvs/shot-scraper-sQHOtKI2/bin/shot-scraper", line 33, in <module>
    sys.exit(load_entry_point('shot-scraper', 'console_scripts', 'shot-scraper')())
  File "/Users/simon/.local/share/virtualenvs/shot-scraper-sQHOtKI2/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/simon/.local/share/virtualenvs/shot-scraper-sQHOtKI2/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/simon/.local/share/virtualenvs/shot-scraper-sQHOtKI2/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/simon/.local/share/virtualenvs/shot-scraper-sQHOtKI2/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/simon/.local/share/virtualenvs/shot-scraper-sQHOtKI2/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/simon/Dropbox/Development/shot-scraper/shot_scraper/cli.py", line 266, in multi
    take_shot(context, shot, fail_on_error=fail_on_error)
  File "/Users/simon/Dropbox/Development/shot-scraper/shot_scraper/cli.py", line 587, in take_shot
    page.screenshot(**screenshot_args)
  File "/Users/simon/.local/share/virtualenvs/shot-scraper-sQHOtKI2/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 7886, in screenshot
    self._sync(
  File "/Users/simon/.local/share/virtualenvs/shot-scraper-sQHOtKI2/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 111, in _sync
    return task.result()
  File "/Users/simon/.local/share/virtualenvs/shot-scraper-sQHOtKI2/lib/python3.10/site-packages/playwright/_impl/_page.py", line 611, in screenshot
    encoded_binary = await self._channel.send("screenshot", params)
  File "/Users/simon/.local/share/virtualenvs/shot-scraper-sQHOtKI2/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/Users/simon/.local/share/virtualenvs/shot-scraper-sQHOtKI2/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 5ms exceeded.
```
I would expect this to keep going, since I didn't specify `--fail-on-error`

Instead, it's failing - because the `TimeoutError` is being raised by the `page.screenshot(...)` method, but the try/catch currently only exists here:

https://github.com/simonw/shot-scraper/blob/3c5e3d11742be513d3ab192f68c582ad6bc77fe0/shot_scraper/cli.py#L544-L547

**Comment by simonw** [comment]
I'm going to have the `take_shot()` function raise the exception itself, then I'll catch it in the `multi()` command.

**Comment by simonw** [comment]
Got this working:
```
% shot-scraper multi ../lots.yml --timeout 5
Timeout 5ms exceeded.
=========================== logs ===========================
navigating to "http://www.example.com/", waiting until "load"
============================================================
Timeout 5ms exceeded.
=========================== logs ===========================
navigating to "https://github.com/", waiting until "load"
============================================================
Timeout 5ms exceeded.
=========================== logs ===========================
navigating to "https://www.w3.org/", waiting until "load"
============================================================
Timeout 5ms exceeded.
=========================== logs ===========================
navigating to "https://simonwillison.net/", waiting until "load"
============================================================
Timeout 5ms exceeded.
=========================== logs ===========================
navigating to "https://simonwillison.net/", waiting until "load"
============================================================
Timeout 5ms exceeded.
=========================== logs ===========================
navigating to "https://simonwillison.net/", waiting until "load"
============================================================
Timeout 5ms exceeded.
=========================== logs ===========================
navigating to "https://simonwillison.net/", waiting until "load"
============================================================
(shot-scraper) e2 % shot-scraper multi ../lots.yml --timeout 5000
Screenshot of 'http://www.example.com/' written to 'example.com.png'
Screenshot of 'https://github.com/' written to 'github-com.png'
Screenshot of 'https://www.w3.org/' written to 'w3c.org.png'
Screenshot of '#bighead' on 'https://simonwillison.net/' written to 'bighead-from-multi.png'
Screenshot of '#bighead' on 'https://simonwillison.net/' written to 'bighead-pink-from-multi.png'
Screenshot of 'https://simonwillison.net/' written to 'simon-narrow-from-multi.png'
Screenshot of 'https://simonwillison.net/' written to 'simon-quality-80-from-multi.png'
```

**Comment by simonw** [comment]
And with `--fail-on-error`:
```
% shot-scraper multi ../lots.yml --timeout 5 --fail-on-error
Error: Timeout 5ms exceeded.
=========================== logs ===========================
navigating to "http://www.example.com/", waiting until "load"
============================================================
```
