### ISSUE TITLE
Issue on Raspberry PI 

### ISSUE THREAD

**Issue by developer2013** [simonw/shot-scraper#60]
Hello, 

I got this error: 

`Traceback (most recent call last):
  File "/usr/bin/shot-scraper", line 33, in <module>
    sys.exit(load_entry_point('shot-scraper==0.10', 'console_scripts', 'shot-scraper')())
  File "/usr/bin/shot-scraper", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: shot-scraper
`

is it not working for the pi? 

thanks
Carsten

**Comment by simonw** [comment]
What version of Python are you running? Could you run `python --version` to check?
